#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD="3463382"
SOURCE_ROOT="${HOME}/Library/Application Support/EVE Frontier"
STAGED_BASE="${HOME}/Library/Application Support/evejs-frontier/macos/staged-client"
CLEAN=false
PATCH_CLIENT_TRUST=true

usage() {
  cat <<'EOF'
Usage: bash StageFrontierClient.sh [options]

Creates an isolated staged copy of the installed EVE Frontier client. The
retail client and shared ResFiles cache are never modified.

Options:
  --build <number>       Installed Frontier build. Default: 3463382
  --source-root <path>   Frontier launcher data root
  --staged-base <path>   Build-numbered staging base
  --clean                Replace this build's existing staged copy
  --no-client-trust-patch
                         Leave blue.so and embedded CA bundles untouched
  -h, --help             Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --build)
      BUILD="$2"
      shift 2
      ;;
    --source-root)
      SOURCE_ROOT="$2"
      shift 2
      ;;
    --staged-base)
      STAGED_BASE="$2"
      shift 2
      ;;
    --clean)
      CLEAN=true
      shift
      ;;
    --no-client-trust-patch)
      PATCH_CLIENT_TRUST=false
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "[evejs-frontier] Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

SOURCE_CACHE="${SOURCE_ROOT}/SharedCache"
SOURCE_APP="${SOURCE_CACHE}/stillness/EVE.app"
SOURCE_BUILD="${SOURCE_APP}/Contents/Resources/build"
SOURCE_RESFILES="${SOURCE_CACHE}/ResFiles"
STAGED_ROOT="${STAGED_BASE}/${BUILD}"
STAGED_CACHE="${STAGED_ROOT}/SharedCache"
STAGED_APP="${STAGED_CACHE}/stillness/EVE.app"
STAGED_BUILD="${STAGED_APP}/Contents/Resources/build"
CURRENT_LINK="${STAGED_BASE}/current"
MARKER="${STAGED_ROOT}/.evejs-frontier-stage.json"

if [[ ! -d "$SOURCE_APP" || ! -d "$SOURCE_RESFILES" ]]; then
  echo "[evejs-frontier] Installed Frontier client is incomplete under: $SOURCE_ROOT" >&2
  exit 1
fi

ACTUAL_BUILD="$(sed -nE 's/^[[:space:]]*build[[:space:]]*=[[:space:]]*([0-9]+).*/\1/p' "${SOURCE_BUILD}/start.ini" | head -n 1)"
if [[ "$ACTUAL_BUILD" != "$BUILD" ]]; then
  echo "[evejs-frontier] Installed build is ${ACTUAL_BUILD:-unknown}, not $BUILD." >&2
  exit 1
fi

if [[ "$CLEAN" == true && -e "$STAGED_ROOT" ]]; then
  if [[ ! -f "$MARKER" ]]; then
    echo "[evejs-frontier] Refusing to clean an unrecognized stage: $STAGED_ROOT" >&2
    exit 1
  fi
  rm -rf "$STAGED_ROOT"
fi

if [[ ! -d "$STAGED_APP" ]]; then
  mkdir -p "${STAGED_CACHE}/stillness"
  echo "[evejs-frontier] Copying the Frontier app into the isolated stage..."
  ditto "$SOURCE_APP" "$STAGED_APP"
fi

if [[ -L "${STAGED_CACHE}/ResFiles" ]]; then
  rm -f "${STAGED_CACHE}/ResFiles"
elif [[ -e "${STAGED_CACHE}/ResFiles" ]]; then
  echo "[evejs-frontier] Refusing to replace non-symlink ResFiles in the stage." >&2
  exit 1
fi
ln -s "$SOURCE_RESFILES" "${STAGED_CACHE}/ResFiles"

cat > "${STAGED_BUILD}/common.ini.tmp" <<'EOF'
; Generated by EveJS-Frontier StageFrontierClient.sh
; The retail start.ini remains untouched.
[main]
cryptoPack = Placebo
EOF
mv "${STAGED_BUILD}/common.ini.tmp" "${STAGED_BUILD}/common.ini"

xattr -dr com.apple.macl "$STAGED_APP" >/dev/null 2>&1 || true
xattr -dr com.apple.quarantine "$STAGED_APP" >/dev/null 2>&1 || true
codesign --remove-signature "$STAGED_APP" >/dev/null 2>&1 || true

BLUE_HASH="$(shasum -a 256 "${STAGED_BUILD}/bin64/blue.so" | awk '{print $1}')"
cat > "$MARKER" <<EOF
{
  "format": "evejs-frontier-stage-v1",
  "build": $BUILD,
  "sourceRoot": $(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$SOURCE_ROOT"),
  "sourceApp": $(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$SOURCE_APP"),
  "blueSoSha256": "$BLUE_HASH",
  "blueSoPatchState": "unmodified",
  "bootCryptoPack": "Placebo",
  "appBundleSignature": "outer-removed",
  "resFilesMode": "symlink"
}
EOF

mkdir -p "$STAGED_BASE"
if [[ -L "$CURRENT_LINK" ]]; then
  rm -f "$CURRENT_LINK"
elif [[ -e "$CURRENT_LINK" ]]; then
  echo "[evejs-frontier] Refusing to replace non-symlink current path: $CURRENT_LINK" >&2
  exit 1
fi
ln -s "./${BUILD}" "$CURRENT_LINK"

if [[ "$PATCH_CLIENT_TRUST" == true ]]; then
  bash "${SCRIPT_DIR}/PatchFrontierClientTrust.sh" --staged-root "$STAGED_ROOT"
  BLUE_HASH="$(shasum -a 256 "${STAGED_BUILD}/bin64/blue.so" | awk '{print $1}')"
fi

echo "[evejs-frontier] Staged client: $STAGED_ROOT"
echo "[evejs-frontier] ResFiles: symlinked to the installed Frontier cache"
if [[ "$PATCH_CLIENT_TRUST" == true ]]; then
  echo "[evejs-frontier] blue.so: manifest verifier patched ($BLUE_HASH)"
  echo "[evejs-frontier] XMPP CA: installed in both embedded client bundles"
  echo "[evejs-frontier] Station docking: enabled in staged code.ccp"
else
  echo "[evejs-frontier] blue.so: unmodified ($BLUE_HASH)"
fi
echo "[evejs-frontier] Boot overlay: common.ini cryptoPack=Placebo"
